=== dietlera15/General_2016/uebung_xml_dietlera15/milch.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT milch (header, produkt, footer)>
	<!ELEMENT header (titel, autor, beschreibung?, adresse?)>
	<!ELEMENT produkt (name, bild, tier, beschreibung?, herkunft, preis)>
	<!ELEMENT footer (autor, adresse, quelle*)>
	
		<!ELEMENT titel (#PCDATA)>
		<!ELEMENT autor (#PCDATA)>
		<!ELEMENT beschreibung (#PCDATA)>
		<!ELEMENT adresse (#PCDATA)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT bild (#PCDATA)>
		<!ELEMENT tier (#PCDATA)>
		<!ELEMENT herkunft (#PCDATA)>
		<!ELEMENT preis (#PCDATA)>
		<!ELEMENT quelle (#PCDATA)>
		
<!ATTLIST produkt typ CDATA #REQUIRED
			menge CDATA #IMPLIED
			fettgehalt CDATA #REQUIRED>
<!ATTLIST bild src CDATA #REQUIRED>
<!ATTLIST quelle link CDATA #IMPLIED>

=== dietlera15/General_2016/uebung_xml_dietlera15/milch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE milch SYSTEM "milch.dtd">

<milch>
	<header>
		<title>Milchprodukte</title>
		<author>Dietler Andreas</author>
		<beschreibung>Uebung zu XML, DTD, XSD und XSLT</beschreibung>
	</header>
	
	<produkt typ="Roh" menge="200ml" fettgehalt="1,25%">
		<name>Milch</name>
		<bild src="img/milch.jpg"/>
		<tier>Milch</tier>
		<beschreibung></beschreibung>
		<herkunft>Österreich</herkunft>
		<preis>1,20€</preis>
	</produkt>
	
	<footer>
		<author>Dietler Andreas</author>
		<adresse>andreas.dietler@edu.fh-joanneum.at</adresse>		
	</footer>
</milch>
